name = "MagMechFEM_Matlab2Julia"
uuid = "64d22085-0e7b-4436-8072-f3b838d60900"
authors = ["Johann Antonio Duffek <LazyScholar@users.noreply.github.com>"]
version = "0.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
