name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6

      # got this from climate machine
      # https://github.com/CliMA/ClimateMachine.jl/tree/master/.github/workflows
      - name: Set GIT config settings
        run: |
            git config user.name "Documenter.jl"
            git config user.email "documenter@juliadocs.github.io"
            git config --global init.defaultBranch main

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -qq install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5 xvfb

      # https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484
      # more info: https://github.com/marketplace/actions/cache
      # TODO: have a look if the compiled/installed julia packages could be cached
      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Install matplotlib (for Plots.jl)
        run: pip3 install matplotlib

      - name: Install Julia dependencies
        env:
          JULIA_PROJECT: "docs/"
        run: |
          julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));'
          julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate();'

      - name: Build and deploy
        # Run with X virtual frame buffer as GR (default backend for Plots.jl) needs
        # an X session to run without warnings
        env:
          JULIA_PROJECT: "docs/"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          XDG_RUNTIME_DIR: "/home/runner"
        run: xvfb-run -- julia --project=docs/ --color=yes docs/make.jl
